language: node_js

cache: yarn

node_js:
  - 8
  - 10

before_install:
  - npm i -g yarn

script:
  - yarn lint
  - yarn build
  - yarn test

# Environment variables marked with `secure` should be securely encrypted as described at:
# https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables

notifications:
  slack:
    rooms:
      - secure: DCwOabhpeifceQmtG5U3FAmtHxrgrhbvYlDh4DoITvSpnBVd+w0W6iByYL8DFkiip4PIznQ+b2vxcI1ss2WIsFYAOw1xBcQltDk8hwioUdcZLBbkFtKN85tcPWwdixm5/FkQndkDjJpzLlMBrouo1e5cfXGNmrYB56Q9q+DJ1FZo6KGMlqog+EYFX9hw4IfEF0f5lNt3my1rQDzErPdPqwG/bZVoohVZYhUCXTSGvJP+VBxKunvk6IDgPI1RQ+fB9xVbi0pk3wUcHpusdzIR1mj1ytZaZFYgeDt2rzxTiiZmhSa3dCogICneOPnXyg3SaluBC2epSZf0Tb1PE6Jmo47N45yqD0GmGtwn5VvXaJpoEoSbZ9acZc73OQVCOBXY6qWcsUV5K7spNHSyLTfzYoaXvd0Kk9I1Ma1/BJVtdg32Tno9S0j9NfMNp7E/udSwFYHGavlrTldNFkTrNoaYjwSBa+MhsghzsDO/5blTZqMwlBUusLfU6tqR/wojF/QMTj1q2q7USilTU67t+o9OvjxdR+5Yhb3gREuJtdH/te1180+J+7Nv585jzymH8HdobLkbXJ6i1TyKtFNBikv2qpt3BoEobaqYdIZ5zJkwMEfqIF1VVEc8kYckPKOaSM/lLN0WYa7tBRxIbD373oWrwqvOv2bVg8xY1YjDo2Gb0XI=
    on_success: change
    on_failure: always

env:
  global:
    - secure: jQNF27j8fUQMPvceembuKF805AqUaGZt5N4tx3L0/raZZd4LUxUAqSD3wVi8oO8rCP8fa5iAgAHeVnQn4hcggRq6hHdgC4kvdWHteUsRjb7CKQPsMycLNarxV+GouLNZgb1iASzWS3gp8U4Bl1aLw/ZKgrYOPwacMQ8ly3RLwzDMRVG/lTtDmqPxSVZySqeWI6IPhMY2A8AKD0jMxNfa1727mHhRMBtcjKZFenREjQsPurJ2P4EfKvHFpEsBWgdJsJ83DgiAUKL0aB3XuljxTZ/Qi6IRG5hSvM2OEzGKv7NUNRZ0en/bI8qTJifDoq6O9zlHy+Ow/xEs48SDtR5KmZw54Yn0kyVrLcQQwDp5f+tcPUZzdH+rNtE/yhQWRTtaRom8tp+kk4XLe9G32LSprEd+5qvGnLhMCQsvRmP7BR2rwMnEhP7PLlVL0anbJBxseMXjW2bMLRquPOLEJ1cwMj+PSlYTr7LjW8ikto5N1JtvCC2XW3JBLZ79PFk12FhLMDVkONdS2wrjtnodshxOEW3go1tzfZyUty911j45TqJ3ZEAJvYPr9ptLSeE2h9MDyYnq22RtcmMVIHVJtU+8Xm78hlElIIG/CLQEzHIZFc60/ZfbldtWASAn2FCq1MR+ma/7AROgz+lC+KV8zuZUuNv2l3zT/D9Dj1pCxHuFfSU=
    - secure: Pc7nr4wL3sRCqIgF19pvtoi+MNDog8UgHcZ2vGuO39oy/UxFv4tc6Xlp7f8+QkOo2Nj+pKM3GDKe7UNg3lIebQm7i6sLvWJwQ9mNywUd3w0tEcWmsXhsbB1Zy0wIGrF1QO3u7FXA3t5d8I4Gado+QK1I3j0kDbnzDhyKpLPowH7uUaYT8Ff1gMzugcKMqw32g4k26ykvkd+jQejVdD/UcsvihLT8nnFUzQLTJ5B3OxO9ykLBlKfNxa2dPkRdMgkAvHCRyDDAsqu93rqFn3LdfcvKvNgZ7XysyAqRoLPflDrR/PKC1Vpm9+W+g8vR7KTbh0eHAT/ZYUPaQe1+V3UaY2Lb3srsuI1xpMViWjlDkslP5kB9bV6RwMh3o1xAy0YCct+0sCXV2m3cndVkiJy4lsg0mHgpUxZqXmA7NIJhBSf4F9sAP6JuSlDC5cwBe15fblmE68TDALHm3e3pXcCJ28B+cAda4mKCAQvy67nwOT2j5zn3CenuFjCopyYfcgogDDyZm67TX9z3Rk33531c/rLa9WnaECxcknbe0gyOd8YNruYy+TbUIcPuzzK59KWFL8LRn2OHTUKloW1WyCtyjTC646kuu9d/DEGcKsgelfsBodkMhS3Yn7RfXJepeDvh2nSPdZppiyGCCIjN9jhQzuGLF/uBMtX5mqny4hXSRxA=
    - secure: DCNz+JAThFV41PCfBvcz1QBqBZVjpXaSF9vVcq/jLy2Rhzoyu6XcPCYQilD868rWMXubSNEPJ9SF7nzvGBCNc+BxO6dxoRDFEa+yzxi9+LqknrrY36KQvATgHEzvLX6YM9CMdNGe+H+z/TG05G/iH1YfpGHDvRvJNjuKXdmOayIB3OQHZljrPS4Vqr0rbINtPo85znWbi1WUhL1a1RSPwmR1F3m2DDxaphm0UsxmpX4Yo6GnyKUUmp25PmdGaHBOO28TxiYQ/TrLrzm9V7OUBLkE2BwxCxK8zMJtwZAGYrr3JKqY5l/YWhdtxYU385j05paRgLA8ruGxqWMSmhEuLGvtxXKrHdk7OQDKDMMWNaTnCnQ+EvOrbbHDTcxDu5b7qjRn3hN4iikEk6w0wi+H9UT412Khe9koiysrMUml3Rfsf9kaAXiLVSv4unPIwO3ACayVUh75KpMkIF0mdEJhbb3q/OSqqwXNdNH6NqKH2JstyTaIwkhc4bCAWAM4TnOMQL4iu4/gIX8g7pIjSuTlYjNCF/Rzoo6XqRI6wCIWXMucveSHDhSuv0Xd+wdMBJo4qgDPKG/EiXblm48FqNH6XUAEBkiba3l0dF4A5OUZ14gYuwxxbfm+B9G00SzfZGkjtcyQbvegUIata6omc/lnkq2Hj7+GXY0okZt5Ijkdjd0=
    - export GIT_AUTHOR_NAME="esg-bot"
    - export GIT_AUTHOR_EMAIL="tech@endemolshine.com"
    - export GIT_COMMITTER_NAME="esg-bot"
    - export GIT_COMMITTER_EMAIL="tech@endemolshine.com"

jobs:
  include:
    - stage: coverage
      if: type != pull_request
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      after_success:
        - yarn global add codecov
        - codecov
    - stage: release
      if: branch = master AND type != pull_request
      after_success:
        - yarn semantic-release
        - git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git fetch --all
        - git merge origin/master
        - git push
